# -*- coding: utf-8 -*-
"""wordsGpFinal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11GzMtBufpJazX6oeKaRtzuz-7bteSwqD
"""

from google.colab import files

print("Select your MS-ASL zip file to upload...")
uploaded = files.upload()

!unzip MS-ASL.zip

import json
import os

# Load the MS-ASL training data
with open('MS-ASL/MSASL_train.json', 'r') as f:
    train_data = json.load(f)

# Load class names
with open('MS-ASL/MSASL_classes.json', 'r') as f:
    classes = json.load(f)

print("=== MS-ASL Dataset Info ===")
print(f"Total training samples: {len(train_data)}")
print(f"Total classes: {len(classes)}")

print("\n=== First entry example ===")
print(json.dumps(train_data[0], indent=2))

print("\n=== Available classes (first 50) ===")
print(classes[:50])

# Check if your words are in the dataset
my_words = ['hello', 'yes', 'no', 'please', 'want', 'sorry', 'help', 'good']

print("\n=== Checking for your words ===")
classes_lower = [c.lower() for c in classes]
for word in my_words:
    if word in classes_lower:
        idx = classes_lower.index(word)
        print(f"  ✓ {word.upper()} - found at index {idx}")
    else:
        print(f"  ✗ {word.upper()} - NOT FOUND")

!pip install yt-dlp

import yt_dlp
import time
import json
import os

# Load data
with open('MS-ASL/MSASL_train.json', 'r') as f:
    train_data = json.load(f)

with open('MS-ASL/MSASL_val.json', 'r') as f:
    val_data = json.load(f)

# Combine train and val
all_data = train_data + val_data

with open('MS-ASL/MSASL_classes.json', 'r') as f:
    classes = json.load(f)

# Your words with their label indices
my_words = ['hello', 'yes', 'no', 'please', 'want', 'sorry', 'help', 'good']
word_to_label = {word: classes.index(word) for word in my_words}

print("=== Word to Label Mapping ===")
for word, label in word_to_label.items():
    print(f"{word}: label {label}")

# Create folders
for word in my_words:
    os.makedirs(f'ms_asl_videos/{word}', exist_ok=True)

# Filter data for your words
print("\n=== Filtering videos by word ===")
word_videos = {word: [] for word in my_words}

for entry in all_data:
    for word, label in word_to_label.items():
        if entry['label'] == label:
            word_videos[word].append(entry)

for word, videos in word_videos.items():
    print(f"{word.upper()}: {len(videos)} videos available")

# Download function
def download_ms_asl_video(entry, output_path):
    """Download a segment from YouTube"""
    start_time = entry['start_time']
    end_time = entry['end_time']
    duration = end_time - start_time

    ydl_opts = {
        'format': 'worst[ext=mp4]',
        'outtmpl': output_path,
        'quiet': True,
        'no_warnings': True,
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.download([entry['url']])

        # Trim to exact segment using ffmpeg
        temp_path = output_path + '.temp.mp4'
        if os.path.exists(output_path):
            cmd = f'ffmpeg -i "{output_path}" -ss {start_time} -t {duration} -c copy "{temp_path}" -y -loglevel quiet'
            os.system(cmd)

            if os.path.exists(temp_path) and os.path.getsize(temp_path) > 1000:
                os.replace(temp_path, output_path)
                return True
            elif os.path.exists(temp_path):
                os.remove(temp_path)

        return os.path.exists(output_path) and os.path.getsize(output_path) > 1000

    except:
        return False

# Download videos
print("\n" + "="*60)
print("=== Downloading MS-ASL Videos ===")
print("="*60)

downloaded = {word: 0 for word in my_words}

for word in my_words:
    print(f"\n{word.upper()}:")
    videos = word_videos[word]

    # Download up to 30 videos per word
    max_videos = min(30, len(videos))

    for i, entry in enumerate(videos[:max_videos]):
        output_path = f"ms_asl_videos/{word}/{word}_{entry['signer_id']}_{i}.mp4"

        # Skip if exists
        if os.path.exists(output_path) and os.path.getsize(output_path) > 1000:
            downloaded[word] += 1
            print(f"  [{i+1}/{max_videos}] Already exists ✓")
            continue

        print(f"  [{i+1}/{max_videos}] Downloading...", end=' ')

        success = download_ms_asl_video(entry, output_path)

        if success:
            downloaded[word] += 1
            print("✓")
        else:
            print("✗")

        time.sleep(1)  # Be nice to YouTube

    print(f"  Total: {downloaded[word]}/{max_videos}")

print("\n" + "="*60)
print("=== Download Summary ===")
print("="*60)
total = 0
for word, count in downloaded.items():
    total += count
    status = "✓" if count >= 10 else "⚠"
    print(f"  {status} {word.upper()}: {count} videos")

print(f"\nTotal downloaded: {total} videos")

!pip uninstall mediapipe -y

!pip install mediapipe==0.10.14

# تأكدي إن MediaPipe اشتغل
import mediapipe as mp
import cv2
import numpy as np
import os

print("✓ All libraries imported successfully!")
print(f"MediaPipe version: {mp.__version__}")

# Test MediaPipe Hands
mp_hands = mp.solutions.hands
hands = mp_hands.Hands(
    static_image_mode=False,
    max_num_hands=2,
    min_detection_confidence=0.5
)

print("✓ MediaPipe Hands initialized!")
print("✓ Ready to extract landmarks!")

# تأكدي إن الفيديوهات موجودة
my_words = ['hello', 'yes', 'no', 'please', 'want', 'sorry', 'help', 'good']

print("\n=== Checking Videos ===")
total = 0
for word in my_words:
    word_dir = f'ms_asl_videos/{word}'
    if os.path.exists(word_dir):
        count = len([f for f in os.listdir(word_dir) if f.endswith('.mp4')])
        total += count
        print(f"{word.upper()}: {count} videos")
    else:
        print(f"{word.upper()}: ❌ not found")

print(f"\nTotal: {total} videos")

if total > 100:
    print("\n✅ Everything is ready! You can start extracting landmarks now!")
else:
    print("\n⚠ Videos are missing. Need to check ms_asl_videos folder.")

import mediapipe as mp
import cv2
import numpy as np
import os
from tqdm import tqdm

# الكلمات اللي عندك
my_words = ['hello', 'yes', 'no', 'please', 'want', 'sorry', 'help', 'good']

# Initialize MediaPipe
mp_hands = mp.solutions.hands
hands = mp_hands.Hands(
    static_image_mode=False,
    max_num_hands=2,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5
)

def extract_landmarks_from_frame(frame, hands_detector):
    """استخراج landmarks من frame واحد مع normalization"""

    # تحويل لـ RGB
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    # معالجة
    result = hands_detector.process(rgb)

    # لو مفيش يد
    if not result.multi_hand_landmarks:
        return np.zeros(63)

    # استخراج أول يد
    hand = result.multi_hand_landmarks[0]
    coords = np.array([[lm.x, lm.y, lm.z] for lm in hand.landmark])  # (21, 3)

    # Normalization
    coords = coords.reshape(21, 3)
    wrist = coords[0]  # المعصم
    coords = coords - wrist  # translate to origin

    # Scale بناءً على حجم الكف
    palm_size = np.linalg.norm(coords[9] - coords[0]) + 1e-6
    coords = coords / palm_size

    return coords.flatten()  # (63,)

def extract_landmarks_from_video(video_path, num_frames=30):
    """
    استخراج landmarks من فيديو كامل
    Returns: (num_frames, 63) أو None لو فشل
    """
    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        return None

    landmarks_sequence = []
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    if total_frames == 0:
        cap.release()
        return None

    # نأخذ frames بالتساوي
    indices = np.linspace(0, total_frames-1, num_frames, dtype=int)

    for idx in indices:
        cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
        ret, frame = cap.read()

        if ret:
            landmarks = extract_landmarks_from_frame(frame, hands)
            landmarks_sequence.append(landmarks)
        else:
            landmarks_sequence.append(np.zeros(63))

    cap.release()

    # تأكد إن عندنا num_frames بالظبط
    while len(landmarks_sequence) < num_frames:
        landmarks_sequence.append(np.zeros(63))

    return np.array(landmarks_sequence[:num_frames])

# معالجة كل الفيديوهات
print("=== Extracting MediaPipe Landmarks from MS-ASL ===\n")

landmarks_data = []
labels = []
word_to_idx = {word: idx for idx, word in enumerate(my_words)}

for word in my_words:
    video_dir = f'ms_asl_videos/{word}'

    if not os.path.exists(video_dir):
        print(f"{word.upper()}: directory not found")
        continue

    video_files = [f for f in os.listdir(video_dir) if f.endswith('.mp4')]
    print(f"{word.upper()}: processing {len(video_files)} videos...")

    success = 0
    for video_file in tqdm(video_files, desc=f"  {word}"):
        video_path = os.path.join(video_dir, video_file)

        # استخراج landmarks
        landmarks = extract_landmarks_from_video(video_path, num_frames=30)

        if landmarks is not None:
            # تأكد إن في يد اتكشفت (مش كله zeros)
            if landmarks.max() > 0:
                landmarks_data.append(landmarks)
                labels.append(word_to_idx[word])
                success += 1

    print(f"  ✓ Success: {success}/{len(video_files)}\n")

# تحويل لـ arrays
X = np.array(landmarks_data)
y = np.array(labels)

print(f"\n{'='*60}")
print(f"Total processed: {len(X)} videos")
print(f"Shape: {X.shape}")  # Should be (N, 30, 63)
print(f"{'='*60}")

# حفظ البيانات
np.save('X_landmarks_msasl.npy', X)
np.save('y_landmarks_msasl.npy', y)

import pickle
with open('word_mapping.pkl', 'wb') as f:
    pickle.dump(word_to_idx, f)

print("\n✓ Landmarks extracted and saved!")
print(f"Word mapping: {word_to_idx}")

hands.close()

# إضافة motion features
print("\n=== Computing Motion Features ===")

X = np.load('X_landmarks_msasl.npy')
print(f"Original shape: {X.shape}")  # (N, 30, 63)

def compute_velocity_acceleration(landmarks_sequence):
    """
    حساب السرعة والتسارع
    Input: (30, 63)
    Output: velocity (30, 63), acceleration (30, 63)
    """

    # Velocity = الفرق بين frames
    velocity = np.diff(landmarks_sequence, axis=0)  # (29, 63)
    velocity = np.vstack([velocity, velocity[-1]])  # pad to (30, 63)

    # Acceleration = الفرق بين velocities
    acceleration = np.diff(velocity, axis=0)  # (29, 63)
    acceleration = np.vstack([acceleration, acceleration[-1]])  # pad to (30, 63)

    return velocity, acceleration

# حساب لكل فيديو
X_velocity = []
X_acceleration = []

for video in X:
    vel, acc = compute_velocity_acceleration(video)
    X_velocity.append(vel)
    X_acceleration.append(acc)

X_velocity = np.array(X_velocity)
X_acceleration = np.array(X_acceleration)

print(f"Velocity shape: {X_velocity.shape}")
print(f"Acceleration shape: {X_acceleration.shape}")

# دمج كل الـ features
X_combined = np.concatenate([X, X_velocity, X_acceleration], axis=2)
print(f"Combined features shape: {X_combined.shape}")  # (N, 30, 189)
# 63 (position) + 63 (velocity) + 63 (acceleration) = 189 features

# حفظ
np.save('X_landmarks_with_motion.npy', X_combined)
print("\n✓ Motion features computed and saved!")

import numpy as np

def augment_landmarks_sequence(landmarks_seq):
    """
    Data augmentation للـ landmarks
    Input: (30, 63)
    Output: (30, 63) augmented
    """

    augmented = landmarks_seq.copy()

    # 1. Horizontal Flip (قلب اليد)
    if np.random.rand() > 0.5:
        augmented = augmented.reshape(30, 21, 3)
        augmented[:, :, 0] = -augmented[:, :, 0]  # flip x-coordinate
        augmented = augmented.reshape(30, 63)

    # 2. Time Warping (تمطيط/ضغط الزمن)
    if np.random.rand() > 0.5:
        # تغيير سرعة الفيديو شوية
        indices = np.sort(np.random.choice(30, size=30, replace=True))
        augmented = augmented[indices]

    # 3. Gaussian Noise (ضوضاء)
    if np.random.rand() > 0.5:
        noise = np.random.randn(*augmented.shape) * 0.01
        augmented = augmented + noise

    # 4. Scale Jitter (تغيير حجم شوية)
    if np.random.rand() > 0.5:
        scale = np.random.uniform(0.9, 1.1)
        augmented = augmented * scale

    return augmented

# تطبيق augmentation
print("\n=== Applying Data Augmentation ===")

X = np.load('X_landmarks_msasl.npy')
y = np.load('y_landmarks_msasl.npy')

# ضاعف البيانات 3 مرات
X_augmented = []
y_augmented = []

for video, label in zip(X, y):
    # Original
    X_augmented.append(video)
    y_augmented.append(label)

    # Augmented version 1
    X_augmented.append(augment_landmarks_sequence(video))
    y_augmented.append(label)

    # Augmented version 2
    X_augmented.append(augment_landmarks_sequence(video))
    y_augmented.append(label)

X_augmented = np.array(X_augmented)
y_augmented = np.array(y_augmented)

print(f"Original size: {len(X)}")
print(f"After augmentation: {len(X_augmented)}")

# حفظ
np.save('X_landmarks_augmented.npy', X_augmented)
np.save('y_landmarks_augmented.npy', y_augmented)

print("\n✓ Augmentation complete!")

# feature_extractor.py - الملف اللي هيستخدمه حسام

import mediapipe as mp
import cv2
import numpy as np

class MSASLFeatureExtractor:
    """
    Feature Extractor لـ MS-ASL Dataset
    يستخدمه حسام للتدريب والـ API
    """

    def __init__(self, num_frames=30):
        self.num_frames = num_frames
        self.mp_hands = mp.solutions.hands
        self.hands = self.mp_hands.Hands(
            static_image_mode=False,
            max_num_hands=2,
            min_detection_confidence=0.5,
            min_tracking_confidence=0.5
        )

    def extract_from_video(self, video_path):
        """
        استخراج landmarks من فيديو
        Returns: (num_frames, 63) أو None
        """
        cap = cv2.VideoCapture(video_path)

        if not cap.isOpened():
            return None

        landmarks_sequence = []
        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

        if total_frames == 0:
            cap.release()
            return None

        # Sample frames uniformly
        indices = np.linspace(0, total_frames-1, self.num_frames, dtype=int)

        for idx in indices:
            cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
            ret, frame = cap.read()

            if ret:
                landmarks = self._extract_from_frame(frame)
                landmarks_sequence.append(landmarks)
            else:
                landmarks_sequence.append(np.zeros(63))

        cap.release()

        # Padding
        while len(landmarks_sequence) < self.num_frames:
            landmarks_sequence.append(np.zeros(63))

        result = np.array(landmarks_sequence[:self.num_frames])

        # Check if hand was detected
        if result.max() == 0:
            return None

        return result

    def _extract_from_frame(self, frame):
        """استخراج من frame واحد مع normalization"""
        rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        result = self.hands.process(rgb)

        if not result.multi_hand_landmarks:
            return np.zeros(63)

        hand = result.multi_hand_landmarks[0]
        coords = np.array([[lm.x, lm.y, lm.z] for lm in hand.landmark])

        # Signer Normalization
        coords = coords.reshape(21, 3)
        wrist = coords[0]
        coords = coords - wrist

        palm_size = np.linalg.norm(coords[9] - coords[0]) + 1e-6
        coords = coords / palm_size

        return coords.flatten()

    def compute_motion_features(self, landmarks_sequence):
        """حساب velocity & acceleration"""
        velocity = np.diff(landmarks_sequence, axis=0)
        velocity = np.vstack([velocity, velocity[-1]])

        acceleration = np.diff(velocity, axis=0)
        acceleration = np.vstack([acceleration, acceleration[-1]])

        return velocity, acceleration

    def extract_full_features(self, video_path):
        """
        استخراج landmarks + motion features
        Returns: (num_frames, 189) - positions + velocity + acceleration
        """
        landmarks = self.extract_from_video(video_path)

        if landmarks is None:
            return None

        velocity, acceleration = self.compute_motion_features(landmarks)

        # Combine all features
        full_features = np.concatenate([landmarks, velocity, acceleration], axis=1)

        return full_features

    def __del__(self):
        if hasattr(self, 'hands'):
            self.hands.close()


# مثال للاستخدام
if __name__ == "__main__":
    extractor = MSASLFeatureExtractor(num_frames=30)

    # Test على فيديو واحد
    features = extractor.extract_from_video('ms_asl_videos/hello/hello_0_0.mp4')

    if features is not None:
        print(f"✓ Features shape: {features.shape}")
        print(f"✓ Hand detected: {features.max() > 0}")
    else:
        print("✗ Failed to extract features")

import mediapipe as mp
import cv2
import numpy as np
import os

# Initialize MediaPipe
mp_hands = mp.solutions.hands
hands = mp_hands.Hands(
    static_image_mode=False,
    max_num_hands=2,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5
)

my_words = ['hello', 'yes', 'no', 'please', 'want', 'sorry', 'help', 'good']

print("=== Debugging Video Extraction ===\n")

# نفحص كل كلمة
for word in my_words:
    video_dir = f'ms_asl_videos/{word}'

    if not os.path.exists(video_dir):
        print(f"{word.upper()}: ❌ Directory not found")
        continue

    video_files = [f for f in os.listdir(video_dir) if f.endswith('.mp4')]

    if len(video_files) == 0:
        print(f"{word.upper()}: ❌ No videos found")
        continue

    # جرب أول فيديو
    test_video = os.path.join(video_dir, video_files[0])
    print(f"\n{word.upper()}: Testing {video_files[0]}")

    # افتح الفيديو
    cap = cv2.VideoCapture(test_video)

    if not cap.isOpened():
        print(f"  ❌ Cannot open video")
        continue

    # معلومات الفيديو
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    fps = cap.get(cv2.CAP_PROP_FPS)
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    print(f"  ℹ Total frames: {total_frames}")
    print(f"  ℹ FPS: {fps}")
    print(f"  ℹ Resolution: {width}x{height}")

    # جرب نقرأ أول frame
    ret, frame = cap.read()

    if not ret:
        print(f"  ❌ Cannot read frame")
        cap.release()
        continue

    print(f"  ✓ Frame read successfully: {frame.shape}")

    # جرب MediaPipe
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    result = hands.process(rgb)

    if result.multi_hand_landmarks:
        print(f"  ✅ Hand detected! {len(result.multi_hand_landmarks)} hand(s)")

        # استخرج landmarks
        hand = result.multi_hand_landmarks[0]
        coords = np.array([[lm.x, lm.y, lm.z] for lm in hand.landmark])
        print(f"  ✓ Landmarks shape: {coords.shape}")
        print(f"  ✓ Landmarks sample: {coords[0]}")  # first landmark
    else:
        print(f"  ⚠ No hand detected in first frame")

    cap.release()

hands.close()
print("\n" + "="*60)

import mediapipe as mp
import cv2
import numpy as np
import os
from tqdm import tqdm

my_words = ['hello', 'yes', 'no', 'please', 'want', 'sorry', 'help', 'good']

# Initialize MediaPipe
mp_hands = mp.solutions.hands
hands = mp_hands.Hands(
    static_image_mode=False,
    max_num_hands=2,
    min_detection_confidence=0.3,  # خفضنا الحد عشان يكتشف أحسن
    min_tracking_confidence=0.3
)

def extract_landmarks_from_frame(frame, hands_detector):
    """استخراج landmarks من frame واحد مع normalization"""

    # تحويل لـ RGB
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    # معالجة
    result = hands_detector.process(rgb)

    # لو مفيش يد
    if not result.multi_hand_landmarks:
        return None  # نرجع None بدل zeros

    # استخراج أول يد
    hand = result.multi_hand_landmarks[0]
    coords = np.array([[lm.x, lm.y, lm.z] for lm in hand.landmark])  # (21, 3)

    # Normalization
    coords = coords.reshape(21, 3)
    wrist = coords[0]  # المعصم
    coords = coords - wrist  # translate to origin

    # Scale بناءً على حجم الكف
    palm_size = np.linalg.norm(coords[9] - coords[0]) + 1e-6
    coords = coords / palm_size

    return coords.flatten()  # (63,)

def extract_landmarks_from_video(video_path, num_frames=30):
    """
    استخراج landmarks من فيديو كامل - VERSION محسنة
    """
    try:
        cap = cv2.VideoCapture(video_path)

        if not cap.isOpened():
            return None

        landmarks_sequence = []
        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

        if total_frames == 0:
            cap.release()
            return None

        # نأخذ frames بالتساوي
        indices = np.linspace(0, total_frames-1, num_frames, dtype=int)

        valid_landmarks = []  # هنا نحط الـ landmarks اللي فيها يد فعلاً

        for idx in indices:
            cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
            ret, frame = cap.read()

            if ret:
                landmarks = extract_landmarks_from_frame(frame, hands)

                if landmarks is not None:  # لو في يد
                    valid_landmarks.append(landmarks)

        cap.release()

        # لو ملقيناش يد في أي frame
        if len(valid_landmarks) == 0:
            return None

        # لو عندنا أقل من نص الـ frames المطلوبة
        if len(valid_landmarks) < num_frames // 2:
            return None

        # نكرر آخر landmark عشان نوصل للعدد المطلوب
        while len(valid_landmarks) < num_frames:
            valid_landmarks.append(valid_landmarks[-1])

        # لو عندنا أكتر من المطلوب، ناخد أول num_frames
        valid_landmarks = valid_landmarks[:num_frames]

        return np.array(valid_landmarks)

    except Exception as e:
        print(f"  Error: {e}")
        return None

# معالجة كل الفيديوهات
print("=== Extracting MediaPipe Landmarks from MS-ASL ===\n")

landmarks_data = []
labels = []
word_to_idx = {word: idx for idx, word in enumerate(my_words)}

success_count = {}
fail_count = {}

for word in my_words:
    video_dir = f'ms_asl_videos/{word}'

    if not os.path.exists(video_dir):
        print(f"{word.upper()}: ❌ directory not found")
        continue

    video_files = [f for f in os.listdir(video_dir) if f.endswith('.mp4')]
    print(f"\n{word.upper()}: processing {len(video_files)} videos...")

    success = 0
    fail = 0

    for video_file in tqdm(video_files, desc=f"  {word}"):
        video_path = os.path.join(video_dir, video_file)

        # استخراج landmarks
        landmarks = extract_landmarks_from_video(video_path, num_frames=30)

        if landmarks is not None:
            landmarks_data.append(landmarks)
            labels.append(word_to_idx[word])
            success += 1
        else:
            fail += 1

    success_count[word] = success
    fail_count[word] = fail
    print(f"  ✓ Success: {success}/{len(video_files)} | ✗ Failed: {fail}")

# تحويل لـ arrays
if len(landmarks_data) > 0:
    X = np.array(landmarks_data)
    y = np.array(labels)

    print(f"\n{'='*60}")
    print(f"Total processed: {len(X)} videos")
    print(f"Shape: {X.shape}")  # Should be (N, 30, 63)
    print(f"{'='*60}")

    # Summary per word
    print("\n=== Summary Per Word ===")
    for word in my_words:
        if word in success_count:
            print(f"{word.upper():10} : ✓ {success_count[word]:2} | ✗ {fail_count[word]:2}")

    # حفظ البيانات
    np.save('X_landmarks_msasl.npy', X)
    np.save('y_landmarks_msasl.npy', y)

    import pickle
    with open('word_mapping.pkl', 'wb') as f:
        pickle.dump(word_to_idx, f)

    print("\n✓ Landmarks extracted and saved!")
    print(f"Files saved:")
    print(f"  - X_landmarks_msasl.npy")
    print(f"  - y_landmarks_msasl.npy")
    print(f"  - word_mapping.pkl")
else:
    print("\n❌ No videos processed successfully!")

hands.close()

# Step 2: Data Augmentation عشان نضاعف البيانات
import numpy as np

X = np.load('X_landmarks_msasl.npy')
y = np.load('y_landmarks_msasl.npy')

print(f"Original data: {X.shape}")

def augment_landmarks(landmarks_seq):
    """Data augmentation"""
    augmented = landmarks_seq.copy()

    # 1. Horizontal Flip
    if np.random.rand() > 0.5:
        augmented = augmented.reshape(30, 21, 3)
        augmented[:, :, 0] = -augmented[:, :, 0]
        augmented = augmented.reshape(30, 63)

    # 2. Gaussian Noise
    if np.random.rand() > 0.5:
        noise = np.random.randn(*augmented.shape) * 0.01
        augmented = augmented + noise

    # 3. Scale
    if np.random.rand() > 0.5:
        scale = np.random.uniform(0.9, 1.1)
        augmented = augmented * scale

    return augmented

# ضاعف البيانات 4 مرات
X_augmented = []
y_augmented = []

for video, label in zip(X, y):
    # Original
    X_augmented.append(video)
    y_augmented.append(label)

    # 3 augmented versions
    for _ in range(3):
        X_augmented.append(augment_landmarks(video))
        y_augmented.append(label)

X_augmented = np.array(X_augmented)
y_augmented = np.array(y_augmented)

print(f"After augmentation: {X_augmented.shape}")
print(f"From {len(X)} → {len(X_augmented)} videos")

# حفظ
np.save('X_landmarks_augmented.npy', X_augmented)
np.save('y_landmarks_augmented.npy', y_augmented)

print("\n✓ Augmentation complete!")
print(f"Now you have ~{len(X_augmented)} training samples")

import numpy as np
import pickle

# Load data
X = np.load('X_landmarks_msasl.npy')
y = np.load('y_landmarks_msasl.npy')

with open('word_mapping.pkl', 'rb') as f:
    word_to_idx = pickle.load(f)

idx_to_word = {v: k for k, v in word_to_idx.items()}

print(f"Original data: {X.shape}")
print(f"Labels: {y.shape}")

# عرض التوزيع الحالي
print("\n=== Original Distribution ===")
for word, idx in word_to_idx.items():
    count = np.sum(y == idx)
    print(f"{word.upper():10} : {count} videos")

def augment_landmarks(landmarks_seq):
    """
    Data augmentation للـ landmarks
    Input: (30, 63)
    Output: (30, 63) augmented
    """
    augmented = landmarks_seq.copy()

    # 1. Horizontal Flip (قلب أفقي - زي المرايا)
    if np.random.rand() > 0.5:
        augmented = augmented.reshape(30, 21, 3)
        augmented[:, :, 0] = -augmented[:, :, 0]  # flip x-coordinate
        augmented = augmented.reshape(30, 63)

    # 2. Gaussian Noise (ضوضاء)
    if np.random.rand() > 0.5:
        noise = np.random.randn(*augmented.shape) * 0.01
        augmented = augmented + noise

    # 3. Scale Jitter (تغيير الحجم شوية)
    if np.random.rand() > 0.5:
        scale = np.random.uniform(0.9, 1.1)
        augmented = augmented * scale

    # 4. Time Warping (تمطيط/ضغط الزمن)
    if np.random.rand() > 0.5:
        # اختار frames عشوائية (مع تكرار)
        indices = np.sort(np.random.choice(30, size=30, replace=True))
        augmented = augmented[indices]

    # 5. Rotation (دوران بسيط)
    if np.random.rand() > 0.5:
        angle = np.random.uniform(-5, 5) * np.pi / 180  # ±5 degrees
        augmented = augmented.reshape(30, 21, 3)

        # Rotate around z-axis
        cos_a = np.cos(angle)
        sin_a = np.sin(angle)

        x = augmented[:, :, 0]
        y = augmented[:, :, 1]

        augmented[:, :, 0] = x * cos_a - y * sin_a
        augmented[:, :, 1] = x * sin_a + y * cos_a

        augmented = augmented.reshape(30, 63)

    return augmented

# ضاعف البيانات 4 مرات (1 original + 3 augmented)
print("\n=== Applying Augmentation ===")

X_augmented = []
y_augmented = []

for i, (video, label) in enumerate(zip(X, y)):
    # 1. Original
    X_augmented.append(video)
    y_augmented.append(label)

    # 2-4. Three augmented versions
    for _ in range(3):
        aug_video = augment_landmarks(video)
        X_augmented.append(aug_video)
        y_augmented.append(label)

    if (i + 1) % 10 == 0:
        print(f"  Processed {i+1}/{len(X)} videos...")

X_augmented = np.array(X_augmented)
y_augmented = np.array(y_augmented)

print(f"\n{'='*60}")
print(f"Original:  {X.shape} videos")
print(f"Augmented: {X_augmented.shape} videos")
print(f"Increase:  {len(X)} → {len(X_augmented)} ({len(X_augmented)/len(X):.1f}x)")
print(f"{'='*60}")

# عرض التوزيع الجديد
print("\n=== After Augmentation Distribution ===")
for word, idx in word_to_idx.items():
    count = np.sum(y_augmented == idx)
    print(f"{word.upper():10} : {count} videos")

# حفظ البيانات
np.save('X_landmarks_augmented.npy', X_augmented)
np.save('y_landmarks_augmented.npy', y_augmented)

print("\n✓ Augmentation complete!")
print(f"\nFiles saved:")
print(f"  - X_landmarks_augmented.npy")
print(f"  - y_landmarks_augmented.npy")
print(f"\nReady for training! 🚀")

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Load augmented data
X = np.load('X_landmarks_augmented.npy')
y = np.load('y_landmarks_augmented.npy')

print(f"Training data: {X.shape}")

# Flatten: (220, 30, 63) → (220, 1890)
X_flat = X.reshape(len(X), -1)
print(f"Flattened: {X_flat.shape}")

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X_flat, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f"\nTrain: {len(X_train)} samples")
print(f"Test:  {len(X_test)} samples")

# Train Random Forest
print("\n=== Training Random Forest ===")

clf = RandomForestClassifier(
    n_estimators=200,
    max_depth=20,
    min_samples_split=2,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

clf.fit(X_train, y_train)

# Evaluate
y_pred = clf.predict(X_test)
accuracy = (y_pred == y_test).mean()

print(f"\n{'='*60}")
print(f"Test Accuracy: {accuracy*100:.2f}%")
print(f"{'='*60}\n")

print("=== Classification Report ===")
my_words = list(word_to_idx.keys())
print(classification_report(y_test, y_pred, target_names=my_words, zero_division=0))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens',
            xticklabels=my_words, yticklabels=my_words)
plt.title('Confusion Matrix - MediaPipe Landmarks + Augmentation',
          fontsize=14, fontweight='bold')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.tight_layout()
plt.savefig('confusion_matrix_augmented.png', dpi=100)
plt.show()

# Save model
import pickle
with open('sign_language_rf_augmented.pkl', 'wb') as f:
    pickle.dump(clf, f)

print("\n✓ Model trained and saved!")
print("Expected accuracy: 50-70% (much better than 17%!)")

# import shutil
# import os

# # # إنشاء مجلد للتسليم
# # output_dir = 'lamiaa_delivery_to_hossam'
# # os.makedirs(output_dir, exist_ok=True)

# print("=== Preparing Files for Hossam ===\n")

# # 1. الـ Feature Extractor Module
# feature_extractor_code = '''"""
# Sign Language Feature Extractor - MediaPipe Landmarks
# Created by: Lamiaa Mahmoud Zaghloul
# Team Beta - SUOLINGO Project

# Usage:
#     from feature_extractor import SignLanguageFeatureExtractor

#     extractor = SignLanguageFeatureExtractor()

#     # Extract from video
#     features = extractor.extract_from_video('path/to/video.mp4')

#     # Predict
#     word, confidence = extractor.predict('path/to/video.mp4')
# """

# import mediapipe as mp
# import cv2
# import numpy as np
# import pickle

# class SignLanguageFeatureExtractor:
#     """
#     Feature Extractor for Sign Language Recognition
#     Uses MediaPipe Hand Landmarks with Signer Normalization
#     """

#     def __init__(self, num_frames=30, model_path='sign_language_rf_augmented.pkl',
#                  word_mapping_path='word_mapping.pkl'):
#         """
#         Initialize the feature extractor

#         Args:
#             num_frames: Number of frames to sample from video (default: 30)
#             model_path: Path to trained model file
#             word_mapping_path: Path to word mapping pickle file
#         """
#         self.num_frames = num_frames
#         self.mp_hands = mp.solutions.hands
#         self.hands = self.mp_hands.Hands(
#             static_image_mode=False,
#             max_num_hands=2,
#             min_detection_confidence=0.3,
#             min_tracking_confidence=0.3
#         )

#         # Load trained model
#         try:
#             with open(model_path, 'rb') as f:
#                 self.model = pickle.load(f)

#             with open(word_mapping_path, 'rb') as f:
#                 self.word_to_idx = pickle.load(f)

#             self.idx_to_word = {v: k for k, v in self.word_to_idx.items()}
#             print(f"✓ Model loaded: {len(self.word_to_idx)} words")
#         except Exception as e:
#             self.model = None
#             print(f"⚠ Model loading failed: {e}")

#     def extract_from_frame(self, frame):
#         """
#         Extract hand landmarks from a single frame

#         Args:
#             frame: Input frame (numpy array, BGR format)

#         Returns:
#             landmarks (63,) array or None if no hand detected
#         """
#         rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
#         result = self.hands.process(rgb)

#         if not result.multi_hand_landmarks:
#             return None

#         # Get first hand
#         hand = result.multi_hand_landmarks[0]
#         coords = np.array([[lm.x, lm.y, lm.z] for lm in hand.landmark])

#         # Signer Normalization:
#         # 1. Translate to wrist origin
#         # 2. Scale by palm size
#         coords = coords.reshape(21, 3)
#         wrist = coords[0]
#         coords = coords - wrist

#         palm_size = np.linalg.norm(coords[9] - coords[0]) + 1e-6
#         coords = coords / palm_size

#         return coords.flatten()

#     def extract_from_video(self, video_path):
#         """
#         Extract landmarks from video file

#         Args:
#             video_path: Path to video file

#         Returns:
#             landmarks array (num_frames, 63) or None if extraction failed
#         """
#         cap = cv2.VideoCapture(video_path)

#         if not cap.isOpened():
#             return None

#         total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
#         if total_frames == 0:
#             cap.release()
#             return None

#         # Sample frames uniformly
#         indices = np.linspace(0, total_frames-1, self.num_frames, dtype=int)
#         valid_landmarks = []

#         for idx in indices:
#             cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
#             ret, frame = cap.read()

#             if ret:
#                 landmarks = self.extract_from_frame(frame)
#                 if landmarks is not None:
#                     valid_landmarks.append(landmarks)

#         cap.release()

#         # Need at least half the frames with detected hands
#         if len(valid_landmarks) < self.num_frames // 2:
#             return None

#         # Pad to num_frames
#         while len(valid_landmarks) < self.num_frames:
#             valid_landmarks.append(valid_landmarks[-1])

#         return np.array(valid_landmarks[:self.num_frames])

#     def predict(self, video_path):
#         """
#         Extract features and predict sign

#         Args:
#             video_path: Path to video file

#         Returns:
#             (predicted_word, confidence) tuple
#             Returns (None, 0.0) if prediction failed
#         """
#         if self.model is None:
#             return None, 0.0

#         features = self.extract_from_video(video_path)

#         if features is None:
#             return None, 0.0

#         # Flatten for Random Forest
#         features_flat = features.reshape(1, -1)

#         # Predict
#         prediction = self.model.predict(features_flat)[0]
#         probabilities = self.model.predict_proba(features_flat)[0]

#         predicted_word = self.idx_to_word[prediction]
#         confidence = probabilities[prediction]

#         return predicted_word, confidence

#     def predict_from_frames(self, frames_list):
#         """
#         Predict from list of frames (for real-time webcam)

#         Args:
#             frames_list: List of frames (numpy arrays)

#         Returns:
#             (predicted_word, confidence) tuple
#         """
#         if self.model is None or len(frames_list) < self.num_frames:
#             return None, 0.0

#         landmarks_sequence = []

#         for frame in frames_list[-self.num_frames:]:
#             landmarks = self.extract_from_frame(frame)
#             if landmarks is not None:
#                 landmarks_sequence.append(landmarks)

#         if len(landmarks_sequence) < self.num_frames // 2:
#             return None, 0.0

#         while len(landmarks_sequence) < self.num_frames:
#             landmarks_sequence.append(landmarks_sequence[-1])

#         features = np.array(landmarks_sequence[:self.num_frames])
#         features_flat = features.reshape(1, -1)

#         prediction = self.model.predict(features_flat)[0]
#         probabilities = self.model.predict_proba(features_flat)[0]

#         predicted_word = self.idx_to_word[prediction]
#         confidence = probabilities[prediction]

#         return predicted_word, confidence

#     def batch_extract(self, video_paths, show_progress=True):
#         """
#         Extract features from multiple videos

#         Args:
#             video_paths: List of video file paths
#             show_progress: Show progress bar

#         Returns:
#             X, y: Feature arrays and labels
#         """
#         X = []
#         failed = []

#         if show_progress:
#             from tqdm import tqdm
#             video_paths = tqdm(video_paths, desc="Extracting")

#         for video_path in video_paths:
#             features = self.extract_from_video(video_path)
#             if features is not None:
#                 X.append(features)
#             else:
#                 failed.append(video_path)

#         print(f"✓ Success: {len(X)}/{len(video_paths)}")
#         if len(failed) > 0:
#             print(f"✗ Failed: {len(failed)} videos")

#         return np.array(X) if len(X) > 0 else None, failed

#     def __del__(self):
#         if hasattr(self, 'hands'):
#             self.hands.close()


# # Example usage
# if __name__ == "__main__":
#     print("Testing Feature Extractor...")

#     extractor = SignLanguageFeatureExtractor()

#     # Test video extraction
#     test_video = "test_video.mp4"
#     word, conf = extractor.predict(test_video)

#     if word:
#         print(f"Predicted: {word.upper()} ({conf*100:.1f}%)")
#     else:
#         print("No hand detected")
# '''

# # حفظ feature_extractor.py
# with open(f'{output_dir}/feature_extractor.py', 'w') as f:
#     f.write(feature_extractor_code)
# print("✓ feature_extractor.py created")

# # 2. نسخ الملفات المهمة
# files_to_copy = [
#     'X_landmarks_msasl.npy',
#     'y_landmarks_msasl.npy',
#     'X_landmarks_augmented.npy',
#     'y_landmarks_augmented.npy',
#     'word_mapping.pkl',
#     'sign_language_rf_augmented.pkl',
#     'confusion_matrix_augmented.png'
# ]

# for file in files_to_copy:
#     if os.path.exists(file):
#         shutil.copy(file, output_dir)
#         print(f"✓ {file} copied")
#     else:
#         print(f"⚠ {file} not found")

# # 3. إنشاء README
# readme = '''# Sign Language Feature Extraction Module
# **Created by:** Lamiaa Mahmoud Zaghloul
# **Team:** Beta - SUOLINGO Project
# **Date:** February 2026

# ## 📦 Contents

# ### Code
# - `feature_extractor.py` - Main module for feature extraction and prediction

# ### Data Files
# - `X_landmarks_msasl.npy` - Original extracted landmarks (55 videos, shape: 55×30×63)
# - `y_landmarks_msasl.npy` - Original labels
# - `X_landmarks_augmented.npy` - Augmented dataset (220 videos, shape: 220×30×63)
# - `y_landmarks_augmented.npy` - Augmented labels
# - `word_mapping.pkl` - Word to index mapping dictionary

# ### Model
# - `sign_language_rf_augmented.pkl` - Trained Random Forest model (95.45% accuracy)
# - `confusion_matrix_augmented.png` - Confusion matrix visualization

# ## 🎯 What I Did

# ### 1. MediaPipe Hand Landmark Extraction
# - Extracts 21 keypoints per hand
# - Each keypoint has (x, y, z) coordinates = 63 features per frame
# - Samples 30 frames uniformly from each video
# - Final shape: (30, 63) per video

# ### 2. Signer Normalization
# - **Translation**: Shifts all landmarks to wrist origin (makes position-invariant)
# - **Scaling**: Normalizes by palm size (makes size-invariant)
# - This ensures the model works across different signers

# ### 3. Data Augmentation
# Applied 5 techniques to increase data from 55 → 220 videos:
# - Horizontal flip (mirror)
# - Gaussian noise (σ=0.01)
# - Scale jitter (0.9-1.1×)
# - Time warping (temporal variation)
# - Rotation (±5°)

# ### 4. Model Training
# - **Algorithm**: Random Forest Classifier
# - **Parameters**: 200 trees, max_depth=20
# - **Input**: 1890 features (30 frames × 63 landmarks)
# - **Output**: 8 sign words
# - **Test Accuracy**: 95.45%

# ## 📊 Performance

# | Word | Precision | Recall | F1-Score |
# |------|-----------|--------|----------|
# | hello | 100% | 100% | 100% |
# | yes | 100% | 100% | 100% |
# | no | 100% | 100% | 100% |
# | please | 86% | 86% | 86% |
# | want | 100% | 100% | 100% |
# | sorry | 100% | 100% | 100% |
# | help | 100% | 75% | 86% |
# | good | 89% | 100% | 94% |

# **Overall Accuracy**: 95.45%

# ## 🚀 Usage for Hossam

# ### Basic Feature Extraction
# ```python
# from feature_extractor import SignLanguageFeatureExtractor

# extractor = SignLanguageFeatureExtractor()

# # Extract from single video
# features = extractor.extract_from_video('path/to/video.mp4')
# print(features.shape)  # (30, 63)

# # Batch extraction
# video_paths = ['video1.mp4', 'video2.mp4', ...]
# X, failed = extractor.batch_extract(video_paths)
# ```

# ### Prediction
# ```python
# # Predict from video file
# word, confidence = extractor.predict('test_video.mp4')
# print(f"Predicted: {word} ({confidence*100:.1f}%)")

# # Real-time from webcam frames
# frames = []  # List of 30 frames
# word, confidence = extractor.predict_from_frames(frames)
# ```

# ### Training CNN-LSTM (For Hossam)
# ```python
# import numpy as np
# from tensorflow.keras import layers, models

# # Load augmented data
# X = np.load('X_landmarks_augmented.npy')  # (220, 30, 63)
# y = np.load('y_landmarks_augmented.npy')

# # Build CNN-LSTM
# model = models.Sequential([
#     layers.TimeDistributed(layers.Dense(128, activation='relu'), input_shape=(30, 63)),
#     layers.TimeDistributed(layers.Dropout(0.3)),
#     layers.LSTM(128, return_sequences=True),
#     layers.LSTM(64),
#     layers.Dropout(0.5),
#     layers.Dense(8, activation='softmax')
# ])

# model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
# model.fit(X, y, epochs=50, batch_size=16, validation_split=0.2)
# ```

# ## 📝 Technical Details

# ### Feature Vector Structure
# ```
# Frame 1: [x0, y0, z0, x1, y1, z1, ..., x20, y20, z20]  (63 values)
# Frame 2: [x0, y0, z0, x1, y1, z1, ..., x20, y20, z20]  (63 values)
# ...
# Frame 30: [x0, y0, z0, x1, y1, z1, ..., x20, y20, z20]  (63 values)

# Total: 30 × 63 = 1890 features per video
# ```

# ### Landmark Index Map
# ```
# 0: Wrist
# 1-4: Thumb
# 5-8: Index finger
# 9-12: Middle finger
# 13-16: Ring finger
# 17-20: Pinky
# ```

# ### Normalization Formula
# ```python
# # 1. Translate to wrist
# coords_normalized = coords - coords[0]  # wrist is index 0

# # 2. Scale by palm size
# palm_size = ||coords[9] - coords[0]||  # distance from wrist to middle finger MCP
# coords_normalized = coords_normalized / palm_size
# ```

# ## ⚠️ Known Issues & Limitations

# 1. **Hand Detection Rate**: ~39% of MS-ASL videos failed (MediaPipe couldn't detect hand)
#    - **Solution**: Use YOLOv8 hand detector as pre-processing OR lower confidence threshold

# 2. **Single Hand Only**: Currently extracts only first detected hand
#    - **Solution**: Can be extended to support two-handed signs

# 3. **Static Background Assumption**: Works best with clear background
#    - **Solution**: Add background subtraction or use green screen data

# ## 🔄 Next Steps (Optional Improvements)

# 1. **Add WLASL Data**: Extract landmarks from WLASL dataset to increase to 300+ videos
# 2. **Motion Features**: Add velocity and acceleration (as computed in Step 2 of code)
# 3. **Transformer Model**: Try attention-based model instead of LSTM
# 4. **Continuous Recognition**: Implement CTC for sentence-level recognition

# ## 📧 Contact
# **Lamiaa Mahmoud Zaghloul**
# Team Beta - Feature Engineering
# lamiaa@example.com

# ---
# *This module is part of the SUOLINGO project - AI-powered sign language learning platform*
# '''

# with open(f'{output_dir}/README.md', 'w') as f:
#     f.write(readme)
# print("✓ README.md created")

# # 4. إنشاء example script
# example_code = '''"""
# Example Usage Script for Hossam
# Run this to test the feature extractor
# """

# from feature_extractor import SignLanguageFeatureExtractor
# import numpy as np

# def test_extraction():
#     """Test basic feature extraction"""
#     print("="*60)
#     print("Testing Feature Extractor")
#     print("="*60)

#     extractor = SignLanguageFeatureExtractor()

#     # Test on a sample video (replace with your video path)
#     test_video = "ms_asl_videos/hello/hello_77_18.mp4"

#     print(f"\\nExtracting from: {test_video}")
#     features = extractor.extract_from_video(test_video)

#     if features is not None:
#         print(f"✓ Features extracted: {features.shape}")
#         print(f"  - Frames: {features.shape[0]}")
#         print(f"  - Landmarks per frame: {features.shape[1]}")
#     else:
#         print("✗ Extraction failed")

#     # Test prediction
#     print(f"\\nPredicting...")
#     word, confidence = extractor.predict(test_video)

#     if word:
#         print(f"✓ Prediction: {word.upper()}")
#         print(f"✓ Confidence: {confidence*100:.1f}%")
#     else:
#         print("✗ Prediction failed")

# def load_augmented_data():
#     """Load the augmented dataset"""
#     print("\\n" + "="*60)
#     print("Loading Augmented Dataset")
#     print("="*60)

#     X = np.load('X_landmarks_augmented.npy')
#     y = np.load('y_landmarks_augmented.npy')

#     print(f"\\nX shape: {X.shape}")
#     print(f"y shape: {y.shape}")
#     print(f"\\nReady for CNN-LSTM training!")

# if __name__ == "__main__":
#     test_extraction()
#     load_augmented_data()
# '''

# with open(f'{output_dir}/example_usage.py', 'w') as f:
#     f.write(example_code)
# print("✓ example_usage.py created")

# # 5. إنشاء zip file
# print("\n=== Creating ZIP file ===")
# shutil.make_archive('lamiaa_delivery_to_hossam', 'zip', output_dir)
# print("✓ lamiaa_delivery_to_hossam.zip created")

# print("\n" + "="*60)
# print("✅ ALL FILES READY FOR HOSSAM!")
# print("="*60)
# print(f"\nDelivery folder: {output_dir}/")
# print(f"ZIP file: lamiaa_delivery_to_hossam.zip")
# print("\nContents:")
# print("  1. feature_extractor.py - Main module")
# print("  2. Data files (.npy)")
# print("  3. Trained model (.pkl)")
# print("  4. README.md - Full documentation")
# print("  5. example_usage.py - Test script")
# print("  6. Confusion matrix visualization")
# print("\n📧 Send lamiaa_delivery_to_hossam.zip to Hossam!")
# print("="*60)

# # real_time_test.py
# # شغليه على اللابتوب: python real_time_test.py

# import cv2
# import numpy as np
# import pickle
# import mediapipe as mp
# from collections import deque
# import time

# # Load model
# with open('sign_language_rf_augmented.pkl', 'rb') as f:
#     model = pickle.load(f)

# with open('word_mapping.pkl', 'rb') as f:
#     word_to_idx = pickle.load(f)

# idx_to_word = {v: k for k, v in word_to_idx.items()}

# # MediaPipe setup
# mp_hands = mp.solutions.hands
# mp_drawing = mp.solutions.drawing_utils
# hands = mp_hands.Hands(
#     static_image_mode=False,
#     max_num_hands=2,
#     min_detection_confidence=0.3,
#     min_tracking_confidence=0.3
# )

# def extract_landmarks(frame):
#     """Extract hand landmarks from frame"""
#     rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
#     result = hands.process(rgb)

#     if not result.multi_hand_landmarks:
#         return None

#     hand = result.multi_hand_landmarks[0]
#     coords = np.array([[lm.x, lm.y, lm.z] for lm in hand.landmark])

#     # Normalization
#     coords = coords.reshape(21, 3)
#     wrist = coords[0]
#     coords = coords - wrist

#     palm_size = np.linalg.norm(coords[9] - coords[0]) + 1e-6
#     coords = coords / palm_size

#     return coords.flatten(), hand

# def predict_sign(landmarks_buffer):
#     """Predict sign from buffer of landmarks"""
#     if len(landmarks_buffer) < 30:
#         return None, 0.0

#     # Take last 30 frames
#     features = np.array(list(landmarks_buffer)[-30:])
#     features_flat = features.reshape(1, -1)

#     # Predict
#     prediction = model.predict(features_flat)[0]
#     probabilities = model.predict_proba(features_flat)[0]

#     predicted_word = idx_to_word[prediction]
#     confidence = probabilities[prediction]

#     return predicted_word, confidence

# # Main loop
# cap = cv2.VideoCapture(0)
# landmarks_buffer = deque(maxlen=30)

# prediction = None
# confidence = 0.0
# last_prediction_time = 0

# print("="*60)
# print("🎥 REAL-TIME SIGN LANGUAGE RECOGNITION")
# print("="*60)
# print("\nInstructions:")
# print("- Position your hand in front of camera")
# print("- Perform a sign and hold it for 1-2 seconds")
# print("- Press 'q' to quit")
# print("- Press 'r' to reset buffer")
# print("\nStarting in 3 seconds...\n")

# time.sleep(3)

# while True:
#     ret, frame = cap.read()
#     if not ret:
#         break

#     # Mirror the frame
#     frame = cv2.flip(frame, 1)

#     # Extract landmarks
#     result = extract_landmarks(frame)

#     if result is not None:
#         landmarks, hand = result
#         landmarks_buffer.append(landmarks)

#         # Draw hand landmarks
#         rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
#         mp_drawing.draw_landmarks(
#             frame, hand, mp_hands.HAND_CONNECTIONS,
#             mp_drawing.DrawingSpec(color=(0, 255, 0), thickness=2, circle_radius=2),
#             mp_drawing.DrawingSpec(color=(255, 0, 0), thickness=2)
#         )

#         # Predict every 0.5 seconds
#         current_time = time.time()
#         if len(landmarks_buffer) >= 30 and (current_time - last_prediction_time) > 0.5:
#             prediction, confidence = predict_sign(landmarks_buffer)
#             last_prediction_time = current_time

#     # Display info
#     height, width = frame.shape[:2]

#     # Buffer status
#     buffer_text = f"Buffer: {len(landmarks_buffer)}/30"
#     cv2.putText(frame, buffer_text, (10, 30),
#                 cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)

#     # Prediction
#     if prediction and confidence > 0.5:
#         text = f"{prediction.upper()}: {confidence*100:.1f}%"

#         # Color based on confidence
#         if confidence > 0.8:
#             color = (0, 255, 0)  # Green - high confidence
#         elif confidence > 0.6:
#             color = (0, 255, 255)  # Yellow - medium
#         else:
#             color = (0, 165, 255)  # Orange - low

#         # Background rectangle
#         text_size = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, 1.2, 3)[0]
#         cv2.rectangle(frame, (10, height - 60),
#                      (20 + text_size[0], height - 10), (0, 0, 0), -1)

#         # Text
#         cv2.putText(frame, text, (15, height - 20),
#                    cv2.FONT_HERSHEY_SIMPLEX, 1.2, color, 3)

#     # Instructions
#     cv2.putText(frame, "Press 'q' to quit | 'r' to reset", (10, height - 80),
#                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (200, 200, 200), 1)

#     # Show frame
#     cv2.imshow('Sign Language Recognition', frame)

#     # Key controls
#     key = cv2.waitKey(1) & 0xFF
#     if key == ord('q'):
#         break
#     elif key == ord('r'):
#         landmarks_buffer.clear()
#         prediction = None
#         print("Buffer reset!")

# cap.release()
# cv2.destroyAllWindows()
# hands.close()

# print("\n✓ Session ended")

# احفظي الـ feature_extractor.py
feature_extractor_code = '''
import mediapipe as mp
import cv2
import numpy as np
import pickle

class SignLanguageFeatureExtractor:
    """Feature Extractor for Sign Language Recognition"""

    def __init__(self, num_frames=30):
        self.num_frames = num_frames
        self.mp_hands = mp.solutions.hands
        self.hands = self.mp_hands.Hands(
            static_image_mode=False,
            max_num_hands=2,
            min_detection_confidence=0.3,
            min_tracking_confidence=0.3
        )

        # Load model
        try:
            with open('sign_language_rf_augmented.pkl', 'rb') as f:
                self.model = pickle.load(f)

            with open('word_mapping.pkl', 'rb') as f:
                self.word_to_idx = pickle.load(f)

            self.idx_to_word = {v: k for k, v in self.word_to_idx.items()}
            print(f"✓ Model loaded: {len(self.word_to_idx)} words")
        except:
            self.model = None
            print("⚠ Model not found")

    def extract_from_frame(self, frame):
        """Extract landmarks from single frame"""
        rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        result = self.hands.process(rgb)

        if not result.multi_hand_landmarks:
            return None

        hand = result.multi_hand_landmarks[0]
        coords = np.array([[lm.x, lm.y, lm.z] for lm in hand.landmark])

        # Normalization
        coords = coords.reshape(21, 3)
        wrist = coords[0]
        coords = coords - wrist

        palm_size = np.linalg.norm(coords[9] - coords[0]) + 1e-6
        coords = coords / palm_size

        return coords.flatten()

    def extract_from_video(self, video_path):
        """Extract landmarks from video file"""
        cap = cv2.VideoCapture(video_path)

        if not cap.isOpened():
            return None

        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        if total_frames == 0:
            cap.release()
            return None

        indices = np.linspace(0, total_frames-1, self.num_frames, dtype=int)
        valid_landmarks = []

        for idx in indices:
            cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
            ret, frame = cap.read()

            if ret:
                landmarks = self.extract_from_frame(frame)
                if landmarks is not None:
                    valid_landmarks.append(landmarks)

        cap.release()

        if len(valid_landmarks) < self.num_frames // 2:
            return None

        while len(valid_landmarks) < self.num_frames:
            valid_landmarks.append(valid_landmarks[-1])

        return np.array(valid_landmarks[:self.num_frames])

    def predict(self, video_path):
        """Extract and predict"""
        if self.model is None:
            return None, 0.0

        features = self.extract_from_video(video_path)

        if features is None:
            return None, 0.0

        features_flat = features.reshape(1, -1)

        prediction = self.model.predict(features_flat)[0]
        probabilities = self.model.predict_proba(features_flat)[0]

        predicted_word = self.idx_to_word[prediction]
        confidence = probabilities[prediction]

        return predicted_word, confidence

    def predict_from_frames(self, frames_list):
        """Predict from list of frames"""
        if self.model is None or len(frames_list) < self.num_frames:
            return None, 0.0

        landmarks_sequence = []

        for frame in frames_list[-self.num_frames:]:
            landmarks = self.extract_from_frame(frame)
            if landmarks is not None:
                landmarks_sequence.append(landmarks)

        if len(landmarks_sequence) < self.num_frames // 2:
            return None, 0.0

        while len(landmarks_sequence) < self.num_frames:
            landmarks_sequence.append(landmarks_sequence[-1])

        features = np.array(landmarks_sequence[:self.num_frames])
        features_flat = features.reshape(1, -1)

        prediction = self.model.predict(features_flat)[0]
        probabilities = self.model.predict_proba(features_flat)[0]

        predicted_word = self.idx_to_word[prediction]
        confidence = probabilities[prediction]

        return predicted_word, confidence

    def __del__(self):
        if hasattr(self, 'hands'):
            self.hands.close()
'''

# حفظ الملف
with open('feature_extractor.py', 'w') as f:
    f.write(feature_extractor_code)

print("✓ feature_extractor.py created!")

from IPython.display import display, Javascript
from google.colab.output import eval_js
from google.colab.patches import cv2_imshow
from base64 import b64decode
import cv2
import numpy as np
from PIL import Image
import io
import time
from feature_extractor import SignLanguageFeatureExtractor

# Load extractor
extractor = SignLanguageFeatureExtractor()

print("✓ Feature extractor loaded!")
print("✓ Ready for webcam test!\n")

def take_photo(quality=0.8):
    """Capture photo from webcam"""
    js = Javascript('''
        async function takePhoto(quality) {
            const div = document.createElement('div');
            const video = document.createElement('video');
            video.style.display = 'block';
            const stream = await navigator.mediaDevices.getUserMedia({video: true});

            document.body.appendChild(div);
            div.appendChild(video);
            video.srcObject = stream;
            await video.play();

            await new Promise(resolve => setTimeout(resolve, 300));

            const canvas = document.createElement('canvas');
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;
            canvas.getContext('2d').drawImage(video, 0, 0);
            stream.getVideoTracks()[0].stop();
            div.remove();
            return canvas.toDataURL('image/jpeg', quality);
        }
    ''')
    display(js)
    data = eval_js('takePhoto({})'.format(quality))
    return data

def base64_to_frame(img_data):
    """Convert base64 to OpenCV frame"""
    img_bytes = b64decode(img_data.split(',')[1])
    img = Image.open(io.BytesIO(img_bytes))
    img = np.array(img)

    if len(img.shape) == 3 and img.shape[2] == 3:
        img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)

    return img

def webcam_sign_test():
    """Test sign recognition with webcam"""

    print("="*70)
    print("🎥 WEBCAM SIGN LANGUAGE TEST")
    print("="*70)

    print("\n📋 Instructions:")
    print("  1. اختاري الكلمة اللي عايزة تجربها")
    print("  2. لما تكوني جاهزة، اضغطي ENTER")
    print("  3. اعملي الإشارة وخليها ثابتة")
    print("  4. الكاميرا هتصور 30 frame (حوالي 3 ثواني)")
    print("  5. هتشوفي التوقع والـ confidence\n")

    words = ['hello', 'yes', 'no', 'please', 'want', 'sorry', 'help', 'good']

    print("الكلمات المتاحة:")
    for i, word in enumerate(words, 1):
        print(f"  {i}. {word.upper()}")

    print("\n" + "="*70)

    # Statistics
    total_tests = 0
    correct_tests = 0
    results_per_word = {word: {'total': 0, 'correct': 0} for word in words}

    while True:
        try:
            choice = input("\nاختاري رقم الكلمة (1-8) أو 'q' للخروج أو 's' لعرض الإحصائيات: ").strip()

            if choice.lower() == 'q':
                # Show final statistics
                if total_tests > 0:
                    print("\n" + "="*70)
                    print("📊 FINAL STATISTICS")
                    print("="*70)
                    accuracy = (correct_tests / total_tests) * 100
                    print(f"\nTotal Tests: {total_tests}")
                    print(f"Correct: {correct_tests}")
                    print(f"Wrong: {total_tests - correct_tests}")
                    print(f"Accuracy: {accuracy:.1f}%")

                    print("\n📈 Per-Word Results:")
                    for word in words:
                        stats = results_per_word[word]
                        if stats['total'] > 0:
                            word_acc = (stats['correct'] / stats['total']) * 100
                            print(f"  {word.upper():10} : {stats['correct']}/{stats['total']} ({word_acc:.0f}%)")

                print("\n✓ Test ended")
                break

            if choice.lower() == 's':
                # Show statistics
                if total_tests > 0:
                    print("\n" + "="*70)
                    print("📊 CURRENT STATISTICS")
                    print("="*70)
                    accuracy = (correct_tests / total_tests) * 100
                    print(f"\nTotal Tests: {total_tests}")
                    print(f"Correct: {correct_tests}")
                    print(f"Accuracy: {accuracy:.1f}%")
                else:
                    print("\n⚠ No tests yet!")
                continue

            idx = int(choice) - 1
            if 0 <= idx < len(words):
                test_word = words[idx]
            else:
                print("❌ رقم غلط! اختاري من 1 لـ 8")
                continue

        except:
            print("❌ رقم غلط! اختاري من 1 لـ 8")
            continue

        print(f"\n{'='*70}")
        print(f"🎯 Testing word: {test_word.upper()}")
        print(f"{'='*70}")

        input("\nاضغطي ENTER لما تكوني جاهزة...")

        print("\n🔴 Starting in...")
        for i in range(3, 0, -1):
            print(f"   {i}...")
            time.sleep(1)

        print("   GO! اعملي الإشارة دلوقتي! 📸\n")

        # Capture 30 frames
        frames = []
        num_frames = 30

        for i in range(num_frames):
            img_data = take_photo(quality=0.5)
            frame = base64_to_frame(img_data)
            frames.append(frame)

            print(f"📸 Frame {i+1}/{num_frames} captured", end='\r')
            time.sleep(0.1)

        print(f"\n\n✓ Captured {len(frames)} frames!")
        print("🔄 Processing...\n")

        # Predict
        predicted_word, confidence = extractor.predict_from_frames(frames)

        print("="*70)
        print("📊 RESULTS")
        print("="*70)

        total_tests += 1
        results_per_word[test_word]['total'] += 1

        if predicted_word:
            print(f"\n🎯 Expected:  {test_word.upper()}")
            print(f"🤖 Predicted: {predicted_word.upper()}")
            print(f"📊 Confidence: {confidence*100:.1f}%")

            # Check if correct
            if predicted_word == test_word:
                correct_tests += 1
                results_per_word[test_word]['correct'] += 1

                print("\n✅✅✅ CORRECT! مبروك! ✅✅✅")
                if confidence > 0.8:
                    print("🌟 High confidence - Perfect!")
                elif confidence > 0.6:
                    print("👍 Good confidence")
                else:
                    print("⚠️ Low confidence - Try again with clearer position")
            else:
                print(f"\n❌ WRONG - Model predicted '{predicted_word}' instead of '{test_word}'")
                print("\n💡 Tips:")
                print("   - تأكدي إن يدك واضحة في الكاميرا")
                print("   - حسّني الإضاءة")
                print("   - اعملي الإشارة ببطء وبوضوح")
        else:
            print("\n❌ Failed to detect hand")
            print("\n💡 Try again with better hand visibility")

        print("\n" + "="*70)

        # Current accuracy
        current_acc = (correct_tests / total_tests) * 100
        print(f"\n📈 Current Accuracy: {correct_tests}/{total_tests} ({current_acc:.1f}%)")
        print("="*70)

# Run the test
webcam_sign_test()

# from google.colab import files
# files.download('sign_language_rf_augmented.pkl')
# files.download('word_mapping.pkl')