# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from google.colab import files

print("Select your MS-ASL zip file to upload...")
uploaded = files.upload()

!unzip MS-ASL.zip

import json
import os

# Load the MS-ASL training data
with open('MS-ASL/MSASL_train.json', 'r') as f:
    train_data = json.load(f)

# Load class names
with open('MS-ASL/MSASL_classes.json', 'r') as f:
    classes = json.load(f)

# Check if your words are in the dataset
my_words = ['eat', 'drink', 'sleep', 'home', 'bathroom', 'morning', 'night', 'work','hello', 'yes', 'no', 'please', 'want', 'sorry', 'help', 'good','school', 'hospital', 'go', 'walk', 'stop', 'here', 'where', 'outside','i','today','you','now']

print("\n=== Checking for your words ===")
classes_lower = [c.lower() for c in classes]
for word in my_words:
    if word in classes_lower:
        idx = classes_lower.index(word)
        print(f"  ✓ {word.upper()} - found at index {idx}")
    else:
        print(f"  ✗ {word.upper()} - NOT FOUND")

!pip install mediapipe==0.10.20

import mediapipe as mp

!pip install -U yt-dlp

import yt_dlp
import time
import json
import os

# Load data
with open('MS-ASL/MSASL_train.json', 'r') as f:
    train_data = json.load(f)

with open('MS-ASL/MSASL_val.json', 'r') as f:
    val_data = json.load(f)

# Combine train and val
all_data = train_data + val_data

with open('MS-ASL/MSASL_classes.json', 'r') as f:
    classes = json.load(f)

# Your words with their label indices
my_words = ['eat', 'drink', 'sleep', 'home', 'bathroom', 'morning', 'night', 'work','hello', 'yes', 'no', 'please', 'want', 'sorry', 'help', 'good','school', 'hospital', 'go', 'walk', 'stop', 'here', 'where', 'outside','i','today','you','now']
word_to_label = {word: classes.index(word) for word in my_words}

print("=== Word to Label Mapping ===")
for word, label in word_to_label.items():
    print(f"{word}: label {label}")

# Create folders
for word in my_words:
    os.makedirs(f'ms_asl_videos/{word}', exist_ok=True)

# Filter data for your words
print("\n=== Filtering videos by word ===")
word_videos = {word: [] for word in my_words}

for entry in all_data:
    for word, label in word_to_label.items():
        if entry['label'] == label:
            word_videos[word].append(entry)

for word, videos in word_videos.items():
    print(f"{word.upper()}: {len(videos)} videos available")

# Download function
def download_ms_asl_video(entry, output_path):
    """Download a segment from YouTube"""
    start_time = entry['start_time']
    end_time = entry['end_time']
    duration = end_time - start_time

    ydl_opts = {
        'format': 'worst[ext=mp4]',
        'outtmpl': output_path,
        'quiet': True,
        'no_warnings': True,
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.download([entry['url']])

        # Trim to exact segment using ffmpeg
        temp_path = output_path + '.temp.mp4'
        if os.path.exists(output_path):
            cmd = f'ffmpeg -i "{output_path}" -ss {start_time} -t {duration} -c copy "{temp_path}" -y -loglevel quiet'
            os.system(cmd)

            if os.path.exists(temp_path) and os.path.getsize(temp_path) > 1000:
                os.replace(temp_path, output_path)
                return True
            elif os.path.exists(temp_path):
                os.remove(temp_path)

        return os.path.exists(output_path) and os.path.getsize(output_path) > 1000

    except:
        return False

# Download videos
print("\n" + "="*60)
print("=== Downloading MS-ASL Videos ===")
print("="*60)

downloaded = {word: 0 for word in my_words}

for word in my_words:
    print(f"\n{word.upper()}:")
    videos = word_videos[word]

    # Download up to 30 videos per word
    max_videos = min(30, len(videos))

    for i, entry in enumerate(videos[:max_videos]):
        output_path = f"ms_asl_videos/{word}/{word}_{entry['signer_id']}_{i}.mp4"

        # Skip if exists
        if os.path.exists(output_path) and os.path.getsize(output_path) > 1000:
            downloaded[word] += 1
            print(f"  [{i+1}/{max_videos}] Already exists ✓")
            continue

        print(f"  [{i+1}/{max_videos}] Downloading...", end=' ')

        success = download_ms_asl_video(entry, output_path)

        if success:
            downloaded[word] += 1
            print("✓")
        else:
            print("✗")

        time.sleep(1)  # Be nice to YouTube

    print(f"  Total: {downloaded[word]}/{max_videos}")

print("\n" + "="*60)
print("=== Download Summary ===")
print("="*60)
total = 0
for word, count in downloaded.items():
    total += count
    status = "✓" if count >= 10 else "⚠"
    print(f"  {status} {word.upper()}: {count} videos")

print(f"\nTotal downloaded: {total} videos")

import cv2
import numpy as np
import os

print("✓ All libraries imported successfully!")
print(f"MediaPipe version: {mp.__version__}")

# Test MediaPipe Hands
mp_hands = mp.solutions.hands
hands = mp_hands.Hands(
    static_image_mode=False,
    max_num_hands=2,
    min_detection_confidence=0.5
)

print("✓ MediaPipe Hands initialized!")
print("✓ Ready to extract landmarks!")

# تأكدي إن الفيديوهات موجودة
my_words = ['eat', 'drink', 'sleep', 'home', 'bathroom', 'morning', 'night', 'work','hello', 'yes', 'no', 'please', 'want', 'sorry', 'help', 'good','school', 'hospital', 'go', 'walk', 'stop', 'here', 'where', 'outside','i','today','you','now']

print("\n=== Checking Videos ===")
total = 0
for word in my_words:
    word_dir = f'ms_asl_videos/{word}'
    if os.path.exists(word_dir):
        count = len([f for f in os.listdir(word_dir) if f.endswith('.mp4')])
        total += count
        print(f"{word.upper()}: {count} videos")
    else:
        print(f"{word.upper()}: ❌ not found")

print(f"\nTotal: {total} videos")

if total > 100:
    print("\n✅ Everything is ready! You can start extracting landmarks now!")
else:
    print("\n⚠ Videos are missing. Need to check ms_asl_videos folder.")

import mediapipe as mp
import cv2
import numpy as np
import os
from tqdm import tqdm

# الكلمات اللي عندك
my_words = ['eat', 'drink', 'sleep', 'home', 'bathroom', 'morning', 'night', 'work','hello', 'yes', 'no', 'please', 'want', 'sorry', 'help', 'good','school', 'hospital', 'go', 'walk', 'stop', 'here', 'where', 'outside','i','today','you','now']

# Initialize MediaPipe
mp_hands = mp.solutions.hands
hands = mp_hands.Hands(
    static_image_mode=False,
    max_num_hands=2,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5
)

def extract_landmarks_from_frame(frame, hands_detector):
    """استخراج landmarks من frame واحد مع normalization"""

    # تحويل لـ RGB
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    # معالجة
    result = hands_detector.process(rgb)

    # لو مفيش يد
    if not result.multi_hand_landmarks:
        return np.zeros(63)

    # استخراج أول يد
    hand = result.multi_hand_landmarks[0]
    coords = np.array([[lm.x, lm.y, lm.z] for lm in hand.landmark])  # (21, 3)

    # Normalization
    coords = coords.reshape(21, 3)
    wrist = coords[0]  # المعصم
    coords = coords - wrist  # translate to origin

    # Scale بناءً على حجم الكف
    palm_size = np.linalg.norm(coords[9] - coords[0]) + 1e-6
    coords = coords / palm_size

    return coords.flatten()  # (63,)

def extract_landmarks_from_video(video_path, num_frames=30):
    """
    استخراج landmarks من فيديو كامل
    Returns: (num_frames, 63) أو None لو فشل
    """
    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        return None

    landmarks_sequence = []
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    if total_frames == 0:
        cap.release()
        return None

    # نأخذ frames بالتساوي
    indices = np.linspace(0, total_frames-1, num_frames, dtype=int)

    for idx in indices:
        cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
        ret, frame = cap.read()

        if ret:
            landmarks = extract_landmarks_from_frame(frame, hands)
            landmarks_sequence.append(landmarks)
        else:
            landmarks_sequence.append(np.zeros(63))

    cap.release()

    # تأكد إن عندنا num_frames بالظبط
    while len(landmarks_sequence) < num_frames:
        landmarks_sequence.append(np.zeros(63))

    return np.array(landmarks_sequence[:num_frames])

# معالجة كل الفيديوهات
print("=== Extracting MediaPipe Landmarks from MS-ASL ===\n")

landmarks_data = []
labels = []
word_to_idx = {word: idx for idx, word in enumerate(my_words)}

for word in my_words:
    video_dir = f'ms_asl_videos/{word}'

    if not os.path.exists(video_dir):
        print(f"{word.upper()}: directory not found")
        continue

    video_files = [f for f in os.listdir(video_dir) if f.endswith('.mp4')]
    print(f"{word.upper()}: processing {len(video_files)} videos...")

    success = 0
    for video_file in tqdm(video_files, desc=f"  {word}"):
        video_path = os.path.join(video_dir, video_file)

        # استخراج landmarks
        landmarks = extract_landmarks_from_video(video_path, num_frames=30)

        if landmarks is not None:
            # تأكد إن في يد اتكشفت (مش كله zeros)
            if landmarks.max() > 0:
                landmarks_data.append(landmarks)
                labels.append(word_to_idx[word])
                success += 1

    print(f"  ✓ Success: {success}/{len(video_files)}\n")

# تحويل لـ arrays
X = np.array(landmarks_data)
y = np.array(labels)

print(f"\n{'='*60}")
print(f"Total processed: {len(X)} videos")
print(f"Shape: {X.shape}")  # Should be (N, 30, 63)
print(f"{'='*60}")

# حفظ البيانات
np.save('X_landmarks_msasl.npy', X)
np.save('y_landmarks_msasl.npy', y)

import pickle
with open('word_mapping.pkl', 'wb') as f:
    pickle.dump(word_to_idx, f)

print("\n✓ Landmarks extracted and saved!")
print(f"Word mapping: {word_to_idx}")

hands.close()

# إضافة motion features
print("\n=== Computing Motion Features ===")

X = np.load('X_landmarks_msasl.npy')
print(f"Original shape: {X.shape}")  # (N, 30, 63)

def compute_velocity_acceleration(landmarks_sequence):
    """
    حساب السرعة والتسارع
    Input: (30, 63)
    Output: velocity (30, 63), acceleration (30, 63)
    """

    # Velocity = الفرق بين frames
    velocity = np.diff(landmarks_sequence, axis=0)  # (29, 63)
    velocity = np.vstack([velocity, velocity[-1]])  # pad to (30, 63)

    # Acceleration = الفرق بين velocities
    acceleration = np.diff(velocity, axis=0)  # (29, 63)
    acceleration = np.vstack([acceleration, acceleration[-1]])  # pad to (30, 63)

    return velocity, acceleration

# حساب لكل فيديو
X_velocity = []
X_acceleration = []

for video in X:
    vel, acc = compute_velocity_acceleration(video)
    X_velocity.append(vel)
    X_acceleration.append(acc)

X_velocity = np.array(X_velocity)
X_acceleration = np.array(X_acceleration)

print(f"Velocity shape: {X_velocity.shape}")
print(f"Acceleration shape: {X_acceleration.shape}")

# دمج كل الـ features
X_combined = np.concatenate([X, X_velocity, X_acceleration], axis=2)
print(f"Combined features shape: {X_combined.shape}")  # (N, 30, 189)
# 63 (position) + 63 (velocity) + 63 (acceleration) = 189 features

# حفظ
np.save('X_landmarks_with_motion.npy', X_combined)
print("\n✓ Motion features computed and saved!")

import numpy as np

def augment_landmarks_sequence(landmarks_seq):
    """
    Data augmentation للـ landmarks
    Input: (30, 63)
    Output: (30, 63) augmented
    """

    augmented = landmarks_seq.copy()

    # 1. Horizontal Flip (قلب اليد)
    if np.random.rand() > 0.5:
        augmented = augmented.reshape(30, 21, 3)
        augmented[:, :, 0] = -augmented[:, :, 0]  # flip x-coordinate
        augmented = augmented.reshape(30, 63)

    # 2. Time Warping (تمطيط/ضغط الزمن)
    if np.random.rand() > 0.5:
        # تغيير سرعة الفيديو شوية
        indices = np.sort(np.random.choice(30, size=30, replace=True))
        augmented = augmented[indices]

    # 3. Gaussian Noise (ضوضاء)
    if np.random.rand() > 0.5:
        noise = np.random.randn(*augmented.shape) * 0.01
        augmented = augmented + noise

    # 4. Scale Jitter (تغيير حجم شوية)
    if np.random.rand() > 0.5:
        scale = np.random.uniform(0.9, 1.1)
        augmented = augmented * scale

    return augmented

# تطبيق augmentation
print("\n=== Applying Data Augmentation ===")

X = np.load('X_landmarks_msasl.npy')
y = np.load('y_landmarks_msasl.npy')

# ضاعف البيانات 3 مرات
X_augmented = []
y_augmented = []

for video, label in zip(X, y):
    # Original
    X_augmented.append(video)
    y_augmented.append(label)

    # Augmented version 1
    X_augmented.append(augment_landmarks_sequence(video))
    y_augmented.append(label)

    # Augmented version 2
    X_augmented.append(augment_landmarks_sequence(video))
    y_augmented.append(label)

X_augmented = np.array(X_augmented)
y_augmented = np.array(y_augmented)

print(f"Original size: {len(X)}")
print(f"After augmentation: {len(X_augmented)}")

# حفظ
np.save('X_landmarks_augmented.npy', X_augmented)
np.save('y_landmarks_augmented.npy', y_augmented)

print("\n✓ Augmentation complete!")

import mediapipe as mp
import cv2
import numpy as np
import os

# Initialize MediaPipe
mp_hands = mp.solutions.hands
hands = mp_hands.Hands(
    static_image_mode=False,
    max_num_hands=2,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5
)

my_words = ['eat', 'drink', 'sleep', 'home', 'bathroom', 'morning', 'night', 'work','hello', 'yes', 'no', 'please', 'want', 'sorry', 'help', 'good','school', 'hospital', 'go', 'walk', 'stop', 'here', 'where', 'outside','i','today','you','now']

print("=== Debugging Video Extraction ===\n")

# نفحص كل كلمة
for word in my_words:
    video_dir = f'ms_asl_videos/{word}'

    if not os.path.exists(video_dir):
        print(f"{word.upper()}: ❌ Directory not found")
        continue

    video_files = [f for f in os.listdir(video_dir) if f.endswith('.mp4')]

    if len(video_files) == 0:
        print(f"{word.upper()}: ❌ No videos found")
        continue

    # جرب أول فيديو
    test_video = os.path.join(video_dir, video_files[0])
    print(f"\n{word.upper()}: Testing {video_files[0]}")

    # افتح الفيديو
    cap = cv2.VideoCapture(test_video)

    if not cap.isOpened():
        print(f"  ❌ Cannot open video")
        continue

    # معلومات الفيديو
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    fps = cap.get(cv2.CAP_PROP_FPS)
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    print(f"  ℹ Total frames: {total_frames}")
    print(f"  ℹ FPS: {fps}")
    print(f"  ℹ Resolution: {width}x{height}")

    # جرب نقرأ أول frame
    ret, frame = cap.read()

    if not ret:
        print(f"  ❌ Cannot read frame")
        cap.release()
        continue

    print(f"  ✓ Frame read successfully: {frame.shape}")

    # جرب MediaPipe
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    result = hands.process(rgb)

    if result.multi_hand_landmarks:
        print(f"  ✅ Hand detected! {len(result.multi_hand_landmarks)} hand(s)")

        # استخرج landmarks
        hand = result.multi_hand_landmarks[0]
        coords = np.array([[lm.x, lm.y, lm.z] for lm in hand.landmark])
        print(f"  ✓ Landmarks shape: {coords.shape}")
        print(f"  ✓ Landmarks sample: {coords[0]}")  # first landmark
    else:
        print(f"  ⚠ No hand detected in first frame")

    cap.release()

hands.close()
print("\n" + "="*60)

import mediapipe as mp
import cv2
import numpy as np
import os
from tqdm import tqdm

my_words = ['eat', 'drink', 'sleep', 'home', 'bathroom', 'morning', 'night', 'work','hello', 'yes', 'no', 'please', 'want', 'sorry', 'help', 'good','school', 'hospital', 'go', 'walk', 'stop', 'here', 'where', 'outside','i','today','you','now']

# Initialize MediaPipe
mp_hands = mp.solutions.hands
hands = mp_hands.Hands(
    static_image_mode=False,
    max_num_hands=2,
    min_detection_confidence=0.3,  # خفضنا الحد عشان يكتشف أحسن
    min_tracking_confidence=0.3
)

def extract_landmarks_from_frame(frame, hands_detector):
    """استخراج landmarks من frame واحد مع normalization"""

    # تحويل لـ RGB
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    # معالجة
    result = hands_detector.process(rgb)

    # لو مفيش يد
    if not result.multi_hand_landmarks:
        return None  # نرجع None بدل zeros

    # استخراج أول يد
    hand = result.multi_hand_landmarks[0]
    coords = np.array([[lm.x, lm.y, lm.z] for lm in hand.landmark])  # (21, 3)

    # Normalization
    coords = coords.reshape(21, 3)
    wrist = coords[0]  # المعصم
    coords = coords - wrist  # translate to origin

    # Scale بناءً على حجم الكف
    palm_size = np.linalg.norm(coords[9] - coords[0]) + 1e-6
    coords = coords / palm_size

    return coords.flatten()  # (63,)

def extract_landmarks_from_video(video_path, num_frames=30):
    """
    استخراج landmarks من فيديو كامل - VERSION محسنة
    """
    try:
        cap = cv2.VideoCapture(video_path)

        if not cap.isOpened():
            return None

        landmarks_sequence = []
        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

        if total_frames == 0:
            cap.release()
            return None

        # نأخذ frames بالتساوي
        indices = np.linspace(0, total_frames-1, num_frames, dtype=int)

        valid_landmarks = []  # هنا نحط الـ landmarks اللي فيها يد فعلاً

        for idx in indices:
            cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
            ret, frame = cap.read()

            if ret:
                landmarks = extract_landmarks_from_frame(frame, hands)

                if landmarks is not None:  # لو في يد
                    valid_landmarks.append(landmarks)

        cap.release()

        # لو ملقيناش يد في أي frame
        if len(valid_landmarks) == 0:
            return None

        # لو عندنا أقل من نص الـ frames المطلوبة
        if len(valid_landmarks) < num_frames // 2:
            return None

        # نكرر آخر landmark عشان نوصل للعدد المطلوب
        while len(valid_landmarks) < num_frames:
            valid_landmarks.append(valid_landmarks[-1])

        # لو عندنا أكتر من المطلوب، ناخد أول num_frames
        valid_landmarks = valid_landmarks[:num_frames]

        return np.array(valid_landmarks)

    except Exception as e:
        print(f"  Error: {e}")
        return None

# معالجة كل الفيديوهات
print("=== Extracting MediaPipe Landmarks from MS-ASL ===\n")

landmarks_data = []
labels = []
word_to_idx = {word: idx for idx, word in enumerate(my_words)}

success_count = {}
fail_count = {}

for word in my_words:
    video_dir = f'ms_asl_videos/{word}'

    if not os.path.exists(video_dir):
        print(f"{word.upper()}: ❌ directory not found")
        continue

    video_files = [f for f in os.listdir(video_dir) if f.endswith('.mp4')]
    print(f"\n{word.upper()}: processing {len(video_files)} videos...")

    success = 0
    fail = 0

    for video_file in tqdm(video_files, desc=f"  {word}"):
        video_path = os.path.join(video_dir, video_file)

        # استخراج landmarks
        landmarks = extract_landmarks_from_video(video_path, num_frames=30)

        if landmarks is not None:
            landmarks_data.append(landmarks)
            labels.append(word_to_idx[word])
            success += 1
        else:
            fail += 1

    success_count[word] = success
    fail_count[word] = fail
    print(f"  ✓ Success: {success}/{len(video_files)} | ✗ Failed: {fail}")

# تحويل لـ arrays
if len(landmarks_data) > 0:
    X = np.array(landmarks_data)
    y = np.array(labels)

    print(f"\n{'='*60}")
    print(f"Total processed: {len(X)} videos")
    print(f"Shape: {X.shape}")  # Should be (N, 30, 63)
    print(f"{'='*60}")

    # Summary per word
    print("\n=== Summary Per Word ===")
    for word in my_words:
        if word in success_count:
            print(f"{word.upper():10} : ✓ {success_count[word]:2} | ✗ {fail_count[word]:2}")

    # حفظ البيانات
    np.save('X_landmarks_msasl.npy', X)
    np.save('y_landmarks_msasl.npy', y)

    import pickle
    with open('word_mapping.pkl', 'wb') as f:
        pickle.dump(word_to_idx, f)

    print("\n✓ Landmarks extracted and saved!")
    print(f"Files saved:")
    print(f"  - X_landmarks_msasl.npy")
    print(f"  - y_landmarks_msasl.npy")
    print(f"  - word_mapping.pkl")
else:
    print("\n❌ No videos processed successfully!")

hands.close()

# Step 2: Data Augmentation عشان نضاعف البيانات
import numpy as np

X = np.load('X_landmarks_msasl.npy')
y = np.load('y_landmarks_msasl.npy')

print(f"Original data: {X.shape}")

def augment_landmarks(landmarks_seq):
    """Data augmentation"""
    augmented = landmarks_seq.copy()

    # 1. Horizontal Flip
    if np.random.rand() > 0.5:
        augmented = augmented.reshape(30, 21, 3)
        augmented[:, :, 0] = -augmented[:, :, 0]
        augmented = augmented.reshape(30, 63)

    # 2. Gaussian Noise
    if np.random.rand() > 0.5:
        noise = np.random.randn(*augmented.shape) * 0.01
        augmented = augmented + noise

    # 3. Scale
    if np.random.rand() > 0.5:
        scale = np.random.uniform(0.9, 1.1)
        augmented = augmented * scale

    return augmented

# ضاعف البيانات 4 مرات
X_augmented = []
y_augmented = []

for video, label in zip(X, y):
    # Original
    X_augmented.append(video)
    y_augmented.append(label)

    # 3 augmented versions
    for _ in range(3):
        X_augmented.append(augment_landmarks(video))
        y_augmented.append(label)

X_augmented = np.array(X_augmented)
y_augmented = np.array(y_augmented)

print(f"After augmentation: {X_augmented.shape}")
print(f"From {len(X)} → {len(X_augmented)} videos")

# حفظ
np.save('X_landmarks_augmented.npy', X_augmented)
np.save('y_landmarks_augmented.npy', y_augmented)

print("\n✓ Augmentation complete!")
print(f"Now you have ~{len(X_augmented)} training samples")

import numpy as np
import pickle

# Load data
X = np.load('X_landmarks_msasl.npy')
y = np.load('y_landmarks_msasl.npy')

with open('word_mapping.pkl', 'rb') as f:
    word_to_idx = pickle.load(f)

idx_to_word = {v: k for k, v in word_to_idx.items()}

print(f"Original data: {X.shape}")
print(f"Labels: {y.shape}")

# عرض التوزيع الحالي
print("\n=== Original Distribution ===")
for word, idx in word_to_idx.items():
    count = np.sum(y == idx)
    print(f"{word.upper():10} : {count} videos")

def augment_landmarks(landmarks_seq):
    """
    Data augmentation للـ landmarks
    Input: (30, 63)
    Output: (30, 63) augmented
    """
    augmented = landmarks_seq.copy()

    # 1. Horizontal Flip (قلب أفقي - زي المرايا)
    if np.random.rand() > 0.5:
        augmented = augmented.reshape(30, 21, 3)
        augmented[:, :, 0] = -augmented[:, :, 0]  # flip x-coordinate
        augmented = augmented.reshape(30, 63)

    # 2. Gaussian Noise (ضوضاء)
    if np.random.rand() > 0.5:
        noise = np.random.randn(*augmented.shape) * 0.01
        augmented = augmented + noise

    # 3. Scale Jitter (تغيير الحجم شوية)
    if np.random.rand() > 0.5:
        scale = np.random.uniform(0.9, 1.1)
        augmented = augmented * scale

    # 4. Time Warping (تمطيط/ضغط الزمن)
    if np.random.rand() > 0.5:
        # اختار frames عشوائية (مع تكرار)
        indices = np.sort(np.random.choice(30, size=30, replace=True))
        augmented = augmented[indices]

    # 5. Rotation (دوران بسيط)
    if np.random.rand() > 0.5:
        angle = np.random.uniform(-5, 5) * np.pi / 180  # ±5 degrees
        augmented = augmented.reshape(30, 21, 3)

        # Rotate around z-axis
        cos_a = np.cos(angle)
        sin_a = np.sin(angle)

        x = augmented[:, :, 0]
        y = augmented[:, :, 1]

        augmented[:, :, 0] = x * cos_a - y * sin_a
        augmented[:, :, 1] = x * sin_a + y * cos_a

        augmented = augmented.reshape(30, 63)

    return augmented

# ضاعف البيانات 4 مرات (1 original + 3 augmented)
print("\n=== Applying Augmentation ===")

X_augmented = []
y_augmented = []

for i, (video, label) in enumerate(zip(X, y)):
    # 1. Original
    X_augmented.append(video)
    y_augmented.append(label)

    # 2-4. Three augmented versions
    for _ in range(3):
        aug_video = augment_landmarks(video)
        X_augmented.append(aug_video)
        y_augmented.append(label)

    if (i + 1) % 10 == 0:
        print(f"  Processed {i+1}/{len(X)} videos...")

X_augmented = np.array(X_augmented)
y_augmented = np.array(y_augmented)

print(f"\n{'='*60}")
print(f"Original:  {X.shape} videos")
print(f"Augmented: {X_augmented.shape} videos")
print(f"Increase:  {len(X)} → {len(X_augmented)} ({len(X_augmented)/len(X):.1f}x)")
print(f"{'='*60}")

# عرض التوزيع الجديد
print("\n=== After Augmentation Distribution ===")
for word, idx in word_to_idx.items():
    count = np.sum(y_augmented == idx)
    print(f"{word.upper():10} : {count} videos")

# حفظ البيانات
np.save('X_landmarks_augmented.npy', X_augmented)
np.save('y_landmarks_augmented.npy', y_augmented)

print("\n✓ Augmentation complete!")
print(f"\nFiles saved:")
print(f"  - X_landmarks_augmented.npy")
print(f"  - y_landmarks_augmented.npy")
print(f"\nReady for training! 🚀")

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Load augmented data
X = np.load('X_landmarks_augmented.npy')
y = np.load('y_landmarks_augmented.npy')

print(f"Training data: {X.shape}")

# Flatten: (220, 30, 63) → (220, 1890)
X_flat = X.reshape(len(X), -1)
print(f"Flattened: {X_flat.shape}")

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X_flat, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f"\nTrain: {len(X_train)} samples")
print(f"Test:  {len(X_test)} samples")

# Train Random Forest
print("\n=== Training Random Forest ===")

clf = RandomForestClassifier(
    n_estimators=200,
    max_depth=20,
    min_samples_split=2,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

clf.fit(X_train, y_train)

# Evaluate
y_pred = clf.predict(X_test)
accuracy = (y_pred == y_test).mean()

print(f"\n{'='*60}")
print(f"Test Accuracy: {accuracy*100:.2f}%")
print(f"{'='*60}\n")

print("=== Classification Report ===")
my_words = list(word_to_idx.keys())
print(classification_report(y_test, y_pred, target_names=my_words, zero_division=0))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens',
            xticklabels=my_words, yticklabels=my_words)
plt.title('Confusion Matrix - MediaPipe Landmarks + Augmentation',
          fontsize=14, fontweight='bold')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.tight_layout()
plt.savefig('confusion_matrix_augmented.png', dpi=100)
plt.show()

# Save model
import pickle
with open('sign_language_rf_augmented.pkl', 'wb') as f:
    pickle.dump(clf, f)

print("\n✓ Model trained and saved!")
print("Expected accuracy: 50-70% (much better than 17%!)")

# احفظي الـ feature_extractor.py
feature_extractor_code = '''
import mediapipe as mp
import cv2
import numpy as np
import pickle

class SignLanguageFeatureExtractor:
    """Feature Extractor for Sign Language Recognition"""

    def __init__(self, num_frames=30):
        self.num_frames = num_frames
        self.mp_hands = mp.solutions.hands
        self.hands = self.mp_hands.Hands(
            static_image_mode=False,
            max_num_hands=2,
            min_detection_confidence=0.3,
            min_tracking_confidence=0.3
        )

        # Load model
        try:
            with open('sign_language_rf_augmented.pkl', 'rb') as f:
                self.model = pickle.load(f)

            with open('word_mapping.pkl', 'rb') as f:
                self.word_to_idx = pickle.load(f)

            self.idx_to_word = {v: k for k, v in self.word_to_idx.items()}
            print(f"✓ Model loaded: {len(self.word_to_idx)} words")
        except:
            self.model = None
            print("⚠ Model not found")

    def extract_from_frame(self, frame):
        """Extract landmarks from single frame"""
        rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        result = self.hands.process(rgb)

        if not result.multi_hand_landmarks:
            return None

        hand = result.multi_hand_landmarks[0]
        coords = np.array([[lm.x, lm.y, lm.z] for lm in hand.landmark])

        # Normalization
        coords = coords.reshape(21, 3)
        wrist = coords[0]
        coords = coords - wrist

        palm_size = np.linalg.norm(coords[9] - coords[0]) + 1e-6
        coords = coords / palm_size

        return coords.flatten()

    def extract_from_video(self, video_path):
        """Extract landmarks from video file"""
        cap = cv2.VideoCapture(video_path)

        if not cap.isOpened():
            return None

        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        if total_frames == 0:
            cap.release()
            return None

        indices = np.linspace(0, total_frames-1, self.num_frames, dtype=int)
        valid_landmarks = []

        for idx in indices:
            cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
            ret, frame = cap.read()

            if ret:
                landmarks = self.extract_from_frame(frame)
                if landmarks is not None:
                    valid_landmarks.append(landmarks)

        cap.release()

        if len(valid_landmarks) < self.num_frames // 2:
            return None

        while len(valid_landmarks) < self.num_frames:
            valid_landmarks.append(valid_landmarks[-1])

        return np.array(valid_landmarks[:self.num_frames])

    def predict(self, video_path):
        """Extract and predict"""
        if self.model is None:
            return None, 0.0

        features = self.extract_from_video(video_path)

        if features is None:
            return None, 0.0

        features_flat = features.reshape(1, -1)

        prediction = self.model.predict(features_flat)[0]
        probabilities = self.model.predict_proba(features_flat)[0]

        predicted_word = self.idx_to_word[prediction]
        confidence = probabilities[prediction]

        return predicted_word, confidence

    def predict_from_frames(self, frames_list):
        """Predict from list of frames"""
        if self.model is None or len(frames_list) < self.num_frames:
            return None, 0.0

        landmarks_sequence = []

        for frame in frames_list[-self.num_frames:]:
            landmarks = self.extract_from_frame(frame)
            if landmarks is not None:
                landmarks_sequence.append(landmarks)

        if len(landmarks_sequence) < self.num_frames // 2:
            return None, 0.0

        while len(landmarks_sequence) < self.num_frames:
            landmarks_sequence.append(landmarks_sequence[-1])

        features = np.array(landmarks_sequence[:self.num_frames])
        features_flat = features.reshape(1, -1)

        prediction = self.model.predict(features_flat)[0]
        probabilities = self.model.predict_proba(features_flat)[0]

        predicted_word = self.idx_to_word[prediction]
        confidence = probabilities[prediction]

        return predicted_word, confidence

    def __del__(self):
        if hasattr(self, 'hands'):
            self.hands.close()
'''

# حفظ الملف
with open('feature_extractor.py', 'w') as f:
    f.write(feature_extractor_code)

print("✓ feature_extractor.py created!")

from google.colab import files
files.download('sign_language_rf_augmented.pkl')
files.download('word_mapping.pkl')

from IPython.display import display, Javascript
from base64 import b64decode
import cv2
import numpy as np
from PIL import Image
import io
import time

from feature_extractor import SignLanguageFeatureExtractor
extractor = SignLanguageFeatureExtractor()

print("✓ Model loaded successfully")

def init_camera():
    display(Javascript("""
        async function initCamera() {
            const video = document.createElement('video');

            const stream = await navigator.mediaDevices.getUserMedia({video: true});
            video.srcObject = stream;

            video.style.width = "400px";
            video.style.border = "3px solid #00ff00";
            video.style.borderRadius = "10px";

            document.body.appendChild(video);

            await video.play();

            window.videoElement = video;
            window.localStream = stream;
        }

        initCamera();
    """))

def take_photo():
    display(Javascript("""
        async function captureFrame() {
            const video = window.videoElement;

            const canvas = document.createElement('canvas');
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;

            canvas.getContext('2d').drawImage(video, 0, 0);

            window.capturedFrame = canvas.toDataURL('image/jpeg', 0.6);
        }

        captureFrame();
    """))

    time.sleep(0.3)
    return eval_js("window.capturedFrame")

def base64_to_frame(img_data):
    img_bytes = b64decode(img_data.split(',')[1])
    img = Image.open(io.BytesIO(img_bytes))
    img = np.array(img)

    if len(img.shape) == 3:
        img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)

    return img

def webcam_sign_test():

    words = [
        'eat','drink','sleep','home','bathroom','morning','night','work',
        'hello','yes','no','please','want','sorry','help','good',
        'school','hospital','go','walk','stop','here','where','outside',
        'i','today','you','now'
    ]

    print("="*60)
    print("🎥 SIGN LANGUAGE TEST")
    print("="*60)

    print("\n📌 Available words:")
    for i, w in enumerate(words, 1):
        print(f"{i:2}. {w}")

    total = 0
    correct = 0

    while True:

        choice = input(f"\nPick word (1-{len(words)}), q to quit: ")

        if choice == 'q':
            break

        try:
            idx = int(choice) - 1
            word = words[idx]
        except:
            print("❌ Invalid")
            continue

        print(f"\n🎯 Show sign for: {word}")
        input("Press ENTER when ready...")

        print("📸 Capturing...")

        frames = []
        num_frames = 20   # optimized

        for i in range(num_frames):
            img_data = take_photo()
            frame = base64_to_frame(img_data)
            frames.append(frame)

            print(f"{i+1}/{num_frames}", end="\r")
            time.sleep(0.1)

        print("\n🔄 Predicting...\n")

        predicted, confidence = extractor.predict_from_frames(frames)

        total += 1

        print("="*40)
        print("RESULT")
        print("="*40)

        print("Expected :", word)
        print("Predicted:", predicted)
        print("Confidence:", confidence)

        if predicted == word:
            correct += 1
            print("✅ Correct!")
        else:
            print("❌ Wrong")

        print(f"\nAccuracy: {correct}/{total} ({(correct/total)*100:.1f}%)")
        print("="*40)

init_camera()
webcam_sign_test()



